### ISSUE TITLE
Address controller not starting: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ErnieAllen** [EnMasseProject/routilities#13]
I'm getting an error when starting the address controller on my work laptop. The same software works fine on a lab box, so it's probably something in my setup.

The log file for the address controller is:
Exception in thread "main" java.lang.NullPointerException
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.process(TemplateOperationsImpl.java:59)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.process(TemplateOperationsImpl.java:39)
	at enmasse.controller.common.OpenShiftHelper.processTemplate(OpenShiftHelper.java:166)
	at enmasse.controller.instance.InstanceManagerImpl.create(InstanceManagerImpl.java:80)
	at enmasse.controller.Controller.<init>(Controller.java:58)
	at enmasse.controller.Controller.main(Controller.java:77)

I'm using:
- openshift-origin-client-tools-v1.5.0-031cbe4-linux-64bit.tar.gz
- latest enmasse
- Fedora 25 - 4.10.10-200.fc25.x86_64 GNU/Linux

Steps:
$ oc cluster down
$ oc cluster up
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.0-rc.0 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... 
   WARNING: Binding DNS on port 8053 instead of 53, which may not be resolvable from all clients.
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.1.38 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.1.38:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

$ oc new-project enmasse
Now using project "enmasse" on server "https://192.168.1.38:8443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git

to build a new example application in Ruby.

$ curl -o enmasse-deploy.sh https://raw.githubusercontent.com/EnMasseProject/enmasse/master/scripts/enmasse-deploy.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6149  100  6149    0     0  14128      0 --:--:-- --:--:-- --:--:-- 14135

$ bash enmasse-deploy.sh -c "https://localhost:8443" -p enmasse
Logged into "https://192.168.1.38:8443" as "developer" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * enmasse
    myproject

Using project "enmasse".
Already on project "enmasse" on server "https://192.168.1.38:8443".
serviceaccount "enmasse-service-account" created
role "view" added: "system:serviceaccount:enmasse:default"
role "edit" added: "system:serviceaccount:enmasse:enmasse-service-account"
configmap "enmasse-template-config" created
deployment "address-controller" created
service "address-controller" created

Then logging into https://192.168.1.38:8443, the address controller hasn't started. The log file is listed above.

**Comment by ErnieAllen** [comment]
This was fixed by removing all the enmasseproject/address-controller images from docker and reloading the latest address-controller.

**Comment by lulf** [comment]
Forgot about this, thanks @ErnieAllen !
