### ISSUE TITLE
Console server is missing retry logic

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/routilities#14]
On 0.8.0, the console will fail to retrieve information from the routers, because the routers are not yet started. When the routers come up, the console does not time out and retry the connection.

**Comment by lulf** [comment]
Deleting the console pod fixes the issue

**Comment by grs** [comment]
Fixed by https://github.com/EnMasseProject/routilities/commit/3ef15dce4a1686caa9b4a51f1a8c95ee9343ff9b
