### ISSUE TITLE
Wrong senders/receivers values for a topic receiver

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/routilities#3]
When a receiver attaches on a topic, the "addresses" tab reports Senders = 2, Receivers = 2 as values.

**Comment by ppatierno** [comment]
I see that with link routing, we have two endpoints in the router and each of them has a "peer". When router stats are read, these two endpoints are taken into account so sender++ and receiver++, the reason why we have Senders=1, Receivers=1 even if I attach only a receiver but considering that it's link routing we have also a sender (on the broker) but it shouldn't be the stats that the user would see right ?
Then the stats are got two times in a row, I see some connectionId that I can't see using qdstat -l on the router. So the reason why Senders=2, Receivers=2.

**Comment by lulf** [comment]
Perhaps it could filter on links that are on the public listener ports 5672/5671?

**Comment by lulf** [comment]
This issue was moved to EnMasseProject/enmasse#60
