### ISSUE TITLE
Subscribers chart doesn't disappear when topic receiver goes to 0

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/routilities#4]
When a receiver connects on a topic, the subscribers chart appears but when the receiver disconnects, it doesn't disappear.

**Comment by ppatierno** [comment]
It seems to me a broker problem, I see that here : 

address.subscription_count = address.queues.length;

in the getAllQueuesAndTopics (artemis.js) , the queue length is always 1 even when the receiver detaches from the topic.

**Comment by lulf** [comment]
This issue was moved to EnMasseProject/enmasse#59
